# Generated by Django 6.0.4 on 2026-04-20 11:09

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=common.utils.UploadTo('user/')),
        ),
    ]
