# Generated by Django 6.0.4 on 2026-05-03 17:33

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=common.utils.UploadTo('users/')),
        ),
    ]
